### ISSUE TITLE
Build new NOSQL table to hold all items

### ISSUE THREAD

**Issue by cujarrett** [cujarrett/destiny-insights-bot#263]
## What

Build new NOSQL table to hold all items

## How

NOSQL schema thoughts for items

- key - `timestamp (itemHash)`
- name
- timestamp
- type
- vendor
- roll

This would allow one database for mods use, Xur exotics, and also now adding armor and mods I think.

Need to solve for vendors who sell the same armor all the time, at "reset" the armor will be the same but the rolls will differ

## Tasks

- [x] - Decide schema for new NOSQL database
- [x] - Stand up new database
- [x] - Fill new database w/ all other database info (consolidate)
- [x] - Update code to use new database
- [x] - Spin down old databases
- [x] - Backup new database

🤔

**Comment by cujarrett** [comment]
Done
